
server:
  port: 8080

spring:
  datasource:
    username: root
    password: zq19970822
    url: jdbc:mysql://localhost:3306/solstice?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: pers.zhaoqi.solstice.entity
