
server:
  port: 8080

spring:
  datasource:
    username: zhaoqi
    password: zq304918243
    url: jdbc:mysql://zhaoqi.cc:3306/solstice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: pers.zhaoqi.solstice.entity

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  level:
      pers:
        zhaoqi:
          solstice:
            userlogin:
              mapper: DEBUG