server:
  port: 8080

spring:
  datasource:
    username: chenliang
    password: chenliang0505
    url: jdbc:mysql://zhaoqi.cc:3306/solstice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: pers.zhaoqi.solstice.entity

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  level:
    pers:
      zhaoqi:
        solstice:
#          brand:
#            mapper: DEBUG
#          dictionary:
#            mapper: DEBUG
#          inventory:
#            mapper: DEBUG
#          log:
#            mapper: DEBUG
#          order:
#            mapper: DEBUG
          product:
            mapper: DEBUG
          shippingaddress:
            mapper: DEBUG
#          trolley:
#            mapper: DEBUG
#          userinfo:
#            mapper: DEBUG
#          userlogin:
#            mapper: DEBUG